require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec_system) do |c|
  c.pattern = "spec/acceptance/**/*_spec.rb"
end

namespace :beaker do
  task :test do
    Rake::Task['rspec_system'].invoke()
  end
end
