name    'sorinaso-cmmi'
version '0.0.1'
source 'https://github.com/sorinaso/puppet-modules/modules/puppet-cmmi'
author 'sorinaso'
license 'Apache License, Version 2.0'
summary './configure && make && make install'
project_page 'https://github.com/sorinaso/puppet-modules/modules/puppet-cmmi'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib'
