HOSTS:
  puppet-modules-test-ubuntu-12042:
    platform: ubuntu-server-12042-x64
    hypervisor: vagrant
    box: panal-puppet-specs
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box
    ip: 192.168.2.98
    distmoduledir : /etc/puppet/modules
    host_name: ubuntu-12042.puppetmodulestest.com